// THIS FILE IS GENERATED by scripts/generate_mock_canvas_data.mjs.
// Do not edit by hand; designer agents must IMPORT from this module
// (read-only). To regenerate after canvas changes:
//
//   node scripts/generate_mock_canvas_data.mjs sar-investigation-test
//
// Provenance:
//   use_case_id     = sar-investigation-test
//   canvas_sha256   = 650233de013e5badb28ffd9585c5325b38aca582bf64c85469e8e90bf0764031
//   generated_at    = 2026-05-11T03:50:30.500Z
//   console_pattern = investigations

export const USE_CASE_ID = "sar-investigation-test";
export const CANVAS_SHA256 = "650233de013e5badb28ffd9585c5325b38aca582bf64c85469e8e90bf0764031";
export const CONSOLE_PATTERN = "investigations";

export interface Borrower {
  id: string;
  name: string;
  naics: string;
  revenue_usd: number;
  geo: string;
  risk_band: string;
}

export const BORROWERS: Borrower[] = [
  {
    "id": "BRW-LECO",
    "name": "Lincoln Electric Holdings",
    "naics": "33",
    "revenue_usd": 4184000000,
    "geo": "OH",
    "risk_band": "1-pass"
  },
  {
    "id": "BRW-BRK",
    "name": "Berkshire Industrial Holdings",
    "naics": "31",
    "revenue_usd": 364000000000,
    "geo": "NE",
    "risk_band": "1-pass"
  },
  {
    "id": "BRW-FORD",
    "name": "Ford Motor Co.",
    "naics": "33",
    "revenue_usd": 158057000000,
    "geo": "MI",
    "risk_band": "2-special-mention"
  },
  {
    "id": "BRW-DEERE",
    "name": "Deere & Company",
    "naics": "33",
    "revenue_usd": 51716000000,
    "geo": "IL",
    "risk_band": "1-pass"
  },
  {
    "id": "BRW-CAT",
    "name": "Caterpillar Inc.",
    "naics": "33",
    "revenue_usd": 67060000000,
    "geo": "IL",
    "risk_band": "1-pass"
  },
  {
    "id": "BRW-GE",
    "name": "GE Aerospace",
    "naics": "33",
    "revenue_usd": 32879000000,
    "geo": "MA",
    "risk_band": "2-special-mention"
  },
  {
    "id": "BRW-HON",
    "name": "Honeywell International",
    "naics": "33",
    "revenue_usd": 36662000000,
    "geo": "NC",
    "risk_band": "1-pass"
  },
  {
    "id": "BRW-EAT",
    "name": "Eaton Corp.",
    "naics": "33",
    "revenue_usd": 23196000000,
    "geo": "OH",
    "risk_band": "1-pass"
  },
  {
    "id": "BRW-3M",
    "name": "3M Company",
    "naics": "33",
    "revenue_usd": 32681000000,
    "geo": "MN",
    "risk_band": "2-special-mention"
  },
  {
    "id": "BRW-EMR",
    "name": "Emerson Electric Co.",
    "naics": "33",
    "revenue_usd": 17492000000,
    "geo": "MO",
    "risk_band": "1-pass"
  },
  {
    "id": "BRW-PH",
    "name": "Parker Hannifin",
    "naics": "33",
    "revenue_usd": 19065000000,
    "geo": "OH",
    "risk_band": "1-pass"
  },
  {
    "id": "BRW-ITW",
    "name": "Illinois Tool Works",
    "naics": "33",
    "revenue_usd": 16106000000,
    "geo": "IL",
    "risk_band": "1-pass"
  }
];

export const PRIMARY_BORROWER = BORROWERS[0];

export interface CaseShape {
  canonical_id: string;
  title: string;
  primary_actor: string;
  decision_kind: string;
  stages: string[];
  key_metrics: string[];
}

export const CASE_SHAPE: CaseShape = {
  "canonical_id": "SAR-2026-04891",
  "title": "Velocity-spike alert — wire-out aggregation across 14 days",
  "primary_actor": "BSA Analyst",
  "decision_kind": "file_sar | dismiss | escalate",
  "stages": [
    "alert",
    "evidence-gathering",
    "investigation",
    "narrative",
    "decision",
    "filed"
  ],
  "key_metrics": [
    "alert_score",
    "structuring_signal",
    "geography_risk"
  ]
};

export const HITL_GATES = [
  "final_approval"
];

export const ATOMIC_SERVICE_STUBS: Record<string, unknown> = {
  "borrower-network": {
    "_stub": "borrower-network",
    "_output_schema": false
  },
  "exposure-aggregator": {
    "_stub": "exposure-aggregator",
    "_output_schema": false
  },
  "peer-and-industry-context": {
    "_stub": "peer-and-industry-context",
    "_output_schema": false
  }
};

export const AGENT_OUTPUT_STUBS: Record<string, unknown> = {
  "complaint-categorizer": {
    "_stub": "complaint-categorizer",
    "_archetype_loaded": true
  },
  "insider-screener": {
    "_stub": "insider-screener",
    "_archetype_loaded": true
  },
  "regulatory-narrator": {
    "_stub": "regulatory-narrator",
    "_archetype_loaded": true
  },
  "narrative-drafter": {
    "_stub": "narrative-drafter",
    "_archetype_loaded": true
  }
};

export const SHARED_RULES = [
  "single_borrower_exposure",
  "insider_aggregate_limit",
  "reg_o_individual_limit"
];

export const RULE_VERDICTS: Record<string, "pass" | "watch" | "fail" | "skip"> = {
  "single_borrower_exposure": "pass",
  "insider_aggregate_limit": "pass",
  "reg_o_individual_limit": "watch"
};

export const PIPELINE_EVENTS = [
  {
    "at": "2026-05-09T08:00:00.000Z",
    "kind": "stage_entered",
    "stage": "intake"
  },
  {
    "at": "2026-05-09T08:00:02.000Z",
    "kind": "document_uploaded",
    "doc_type": "10-K"
  },
  {
    "at": "2026-05-09T08:00:05.000Z",
    "kind": "document_uploaded",
    "doc_type": "AR_aging"
  },
  {
    "at": "2026-05-09T08:00:09.000Z",
    "kind": "stage_entered",
    "stage": "extracting"
  },
  {
    "at": "2026-05-09T08:00:54.000Z",
    "kind": "document_extracted",
    "doc_type": "10-K",
    "confidence": 0.94
  },
  {
    "at": "2026-05-09T08:01:02.000Z",
    "kind": "document_extracted",
    "doc_type": "AR_aging",
    "confidence": 0.91
  },
  {
    "at": "2026-05-09T08:01:04.000Z",
    "kind": "service_invoked",
    "service": "borrower-network",
    "latency_ms": 697
  },
  {
    "at": "2026-05-09T08:01:06.000Z",
    "kind": "service_invoked",
    "service": "exposure-aggregator",
    "latency_ms": 968
  },
  {
    "at": "2026-05-09T08:01:08.000Z",
    "kind": "service_invoked",
    "service": "peer-and-industry-context",
    "latency_ms": 436
  },
  {
    "at": "2026-05-09T08:01:15.000Z",
    "kind": "agent_invoked",
    "agent": "complaint-categorizer",
    "tokens_in": 8000,
    "tokens_out": 3500
  },
  {
    "at": "2026-05-09T08:01:22.000Z",
    "kind": "agent_invoked",
    "agent": "insider-screener",
    "tokens_in": 8000,
    "tokens_out": 3500
  },
  {
    "at": "2026-05-09T08:01:29.000Z",
    "kind": "agent_invoked",
    "agent": "regulatory-narrator",
    "tokens_in": 8000,
    "tokens_out": 3500
  },
  {
    "at": "2026-05-09T08:01:36.000Z",
    "kind": "agent_invoked",
    "agent": "narrative-drafter",
    "tokens_in": 8000,
    "tokens_out": 3500
  },
  {
    "at": "2026-05-09T08:02:36.000Z",
    "kind": "human_action_pending",
    "gate": "final_approval"
  },
  {
    "at": "2026-05-09T08:05:36.000Z",
    "kind": "human_action",
    "gate": "final_approval",
    "decision": "approve"
  },
  {
    "at": "2026-05-09T08:05:38.000Z",
    "kind": "stage_entered",
    "stage": "done"
  }
];

export const MODEL_PROVIDER = "anthropic_api";

export const COMPLIANCE_SCOPE = "full";

// A minimal "live case" that designers can render directly.
export const LIVE_CASE = {
  id: CASE_SHAPE.canonical_id,
  title: CASE_SHAPE.title,
  borrower: PRIMARY_BORROWER,
  current_stage: CASE_SHAPE.stages[CASE_SHAPE.stages.length - 1],
  decision: "approve",
  decision_kind: CASE_SHAPE.decision_kind,
  hitl_gates: HITL_GATES,
  events: PIPELINE_EVENTS,
  rule_verdicts: RULE_VERDICTS,
  service_results: ATOMIC_SERVICE_STUBS,
  agent_outputs: AGENT_OUTPUT_STUBS,
};

// END GENERATED.
