// THIS FILE IS GENERATED by scripts/generate_mock_canvas_data.mjs.
// Do not edit by hand; designer agents must IMPORT from this module
// (read-only). To regenerate after canvas changes:
//
//   node scripts/generate_mock_canvas_data.mjs cre-surveillance-test
//
// Provenance:
//   use_case_id     = cre-surveillance-test
//   canvas_sha256   = 6cbf4ad8f20b2710ddb398c3f1f91cde2a92ea058c90718905df1830a3b0144a
//   generated_at    = 2026-05-11T05:11:42.178Z
//   console_pattern = surveillance

export const USE_CASE_ID = "cre-surveillance-test";
export const CANVAS_SHA256 = "6cbf4ad8f20b2710ddb398c3f1f91cde2a92ea058c90718905df1830a3b0144a";
export const CONSOLE_PATTERN = "surveillance";

export interface Borrower {
  id: string;
  name: string;
  naics: string;
  revenue_usd: number;
  geo: string;
  risk_band: string;
}

export const BORROWERS: Borrower[] = [
  {
    "id": "BRW-LECO",
    "name": "Lincoln Electric Holdings",
    "naics": "33",
    "revenue_usd": 4184000000,
    "geo": "OH",
    "risk_band": "1-pass"
  },
  {
    "id": "BRW-BRK",
    "name": "Berkshire Industrial Holdings",
    "naics": "31",
    "revenue_usd": 364000000000,
    "geo": "NE",
    "risk_band": "1-pass"
  },
  {
    "id": "BRW-FORD",
    "name": "Ford Motor Co.",
    "naics": "33",
    "revenue_usd": 158057000000,
    "geo": "MI",
    "risk_band": "2-special-mention"
  },
  {
    "id": "BRW-DEERE",
    "name": "Deere & Company",
    "naics": "33",
    "revenue_usd": 51716000000,
    "geo": "IL",
    "risk_band": "1-pass"
  },
  {
    "id": "BRW-CAT",
    "name": "Caterpillar Inc.",
    "naics": "33",
    "revenue_usd": 67060000000,
    "geo": "IL",
    "risk_band": "1-pass"
  },
  {
    "id": "BRW-GE",
    "name": "GE Aerospace",
    "naics": "33",
    "revenue_usd": 32879000000,
    "geo": "MA",
    "risk_band": "2-special-mention"
  },
  {
    "id": "BRW-HON",
    "name": "Honeywell International",
    "naics": "33",
    "revenue_usd": 36662000000,
    "geo": "NC",
    "risk_band": "1-pass"
  },
  {
    "id": "BRW-EAT",
    "name": "Eaton Corp.",
    "naics": "33",
    "revenue_usd": 23196000000,
    "geo": "OH",
    "risk_band": "1-pass"
  },
  {
    "id": "BRW-3M",
    "name": "3M Company",
    "naics": "33",
    "revenue_usd": 32681000000,
    "geo": "MN",
    "risk_band": "2-special-mention"
  },
  {
    "id": "BRW-EMR",
    "name": "Emerson Electric Co.",
    "naics": "33",
    "revenue_usd": 17492000000,
    "geo": "MO",
    "risk_band": "1-pass"
  },
  {
    "id": "BRW-PH",
    "name": "Parker Hannifin",
    "naics": "33",
    "revenue_usd": 19065000000,
    "geo": "OH",
    "risk_band": "1-pass"
  },
  {
    "id": "BRW-ITW",
    "name": "Illinois Tool Works",
    "naics": "33",
    "revenue_usd": 16106000000,
    "geo": "IL",
    "risk_band": "1-pass"
  }
];

export const PRIMARY_BORROWER = BORROWERS[0];

export interface CaseShape {
  canonical_id: string;
  title: string;
  primary_actor: string;
  decision_kind: string;
  stages: string[];
  key_metrics: string[];
}

export const CASE_SHAPE: CaseShape = {
  "canonical_id": "CELL-CRE-NORTHEAST-2026Q2",
  "title": "CRE concentration · Northeast region",
  "primary_actor": "Chief Credit Officer",
  "decision_kind": "watch | constrain | breach",
  "stages": [
    "aggregated",
    "compared",
    "decided"
  ],
  "key_metrics": [
    "pct_capital",
    "delta_yoy",
    "rule_status"
  ]
};

export const HITL_GATES = [
  {
    "name": "escalate_to_watchlist",
    "irrevocable": false,
    "description": "Reviewer escalates a facility to watchlist (reversible)"
  },
  {
    "name": "book_specific_reserve",
    "irrevocable": true,
    "description": "Credit committee books a specific reserve (irrevocable)"
  }
];

export const ATOMIC_SERVICE_STUBS: Record<string, unknown> = {
  "industry-risk-scorer": {
    "_stub": "industry-risk-scorer",
    "_output_schema": false
  },
  "peer-and-industry-context": {
    "_stub": "peer-and-industry-context",
    "_output_schema": false
  },
  "exposure-aggregator": {
    "_stub": "exposure-aggregator",
    "_output_schema": false
  }
};

export const AGENT_OUTPUT_STUBS: Record<string, unknown> = {};

export const SHARED_RULES = [
  "cap_rate_band_check",
  "dscr_threshold"
];

export const RULE_VERDICTS: Record<string, "pass" | "watch" | "fail" | "skip"> = {
  "cap_rate_band_check": "pass",
  "dscr_threshold": "pass"
};

export const PIPELINE_EVENTS = [
  {
    "at": "2026-05-09T08:00:00.000Z",
    "kind": "stage_entered",
    "stage": "intake"
  },
  {
    "at": "2026-05-09T08:00:02.000Z",
    "kind": "document_uploaded",
    "doc_type": "10-K"
  },
  {
    "at": "2026-05-09T08:00:05.000Z",
    "kind": "document_uploaded",
    "doc_type": "AR_aging"
  },
  {
    "at": "2026-05-09T08:00:09.000Z",
    "kind": "stage_entered",
    "stage": "extracting"
  },
  {
    "at": "2026-05-09T08:00:54.000Z",
    "kind": "document_extracted",
    "doc_type": "10-K",
    "confidence": 0.94
  },
  {
    "at": "2026-05-09T08:01:02.000Z",
    "kind": "document_extracted",
    "doc_type": "AR_aging",
    "confidence": 0.91
  },
  {
    "at": "2026-05-09T08:01:04.000Z",
    "kind": "service_invoked",
    "service": "industry-risk-scorer",
    "latency_ms": 847
  },
  {
    "at": "2026-05-09T08:01:06.000Z",
    "kind": "service_invoked",
    "service": "peer-and-industry-context",
    "latency_ms": 436
  },
  {
    "at": "2026-05-09T08:01:08.000Z",
    "kind": "service_invoked",
    "service": "exposure-aggregator",
    "latency_ms": 968
  },
  {
    "at": "2026-05-09T08:01:15.000Z",
    "kind": "agent_invoked",
    "agent": "market-context-narrator",
    "tokens_in": 8000,
    "tokens_out": 3500
  },
  {
    "at": "2026-05-09T08:02:15.000Z",
    "kind": "human_action_pending",
    "gate": {
      "name": "escalate_to_watchlist",
      "irrevocable": false,
      "description": "Reviewer escalates a facility to watchlist (reversible)"
    }
  },
  {
    "at": "2026-05-09T08:05:15.000Z",
    "kind": "human_action",
    "gate": {
      "name": "escalate_to_watchlist",
      "irrevocable": false,
      "description": "Reviewer escalates a facility to watchlist (reversible)"
    },
    "decision": "approve"
  },
  {
    "at": "2026-05-09T08:06:15.000Z",
    "kind": "human_action_pending",
    "gate": {
      "name": "book_specific_reserve",
      "irrevocable": true,
      "description": "Credit committee books a specific reserve (irrevocable)"
    }
  },
  {
    "at": "2026-05-09T08:09:15.000Z",
    "kind": "human_action",
    "gate": {
      "name": "book_specific_reserve",
      "irrevocable": true,
      "description": "Credit committee books a specific reserve (irrevocable)"
    },
    "decision": "approve"
  },
  {
    "at": "2026-05-09T08:09:17.000Z",
    "kind": "stage_entered",
    "stage": "done"
  }
];

export const MODEL_PROVIDER = "vertex_gemini";

export const COMPLIANCE_SCOPE = "lightweight";

// A minimal "live case" that designers can render directly.
export const LIVE_CASE = {
  id: CASE_SHAPE.canonical_id,
  title: CASE_SHAPE.title,
  borrower: PRIMARY_BORROWER,
  current_stage: CASE_SHAPE.stages[CASE_SHAPE.stages.length - 1],
  decision: "approve",
  decision_kind: CASE_SHAPE.decision_kind,
  hitl_gates: HITL_GATES,
  events: PIPELINE_EVENTS,
  rule_verdicts: RULE_VERDICTS,
  service_results: ATOMIC_SERVICE_STUBS,
  agent_outputs: AGENT_OUTPUT_STUBS,
};

// END GENERATED.
