// THIS FILE IS GENERATED by scripts/generate_mock_canvas_data.mjs.
// Do not edit by hand; designer agents must IMPORT from this module
// (read-only). To regenerate after canvas changes:
//
//   node scripts/generate_mock_canvas_data.mjs credit-memo-commercial-test
//
// Provenance:
//   use_case_id     = credit-memo-commercial-test
//   canvas_sha256   = 383ab8c261e3159bff64d0389bccc5c467df057512ee56a1b09229d25fbe8251
//   generated_at    = 2026-05-11T00:52:41.629Z
//   console_pattern = pipeline

export const USE_CASE_ID = "credit-memo-commercial-test";
export const CANVAS_SHA256 = "383ab8c261e3159bff64d0389bccc5c467df057512ee56a1b09229d25fbe8251";
export const CONSOLE_PATTERN = "pipeline";

export interface Borrower {
  id: string;
  name: string;
  naics: string;
  revenue_usd: number;
  geo: string;
  risk_band: string;
}

export const BORROWERS: Borrower[] = [
  {
    "id": "BRW-LECO",
    "name": "Lincoln Electric Holdings",
    "naics": "33",
    "revenue_usd": 4184000000,
    "geo": "OH",
    "risk_band": "1-pass"
  },
  {
    "id": "BRW-BRK",
    "name": "Berkshire Industrial Holdings",
    "naics": "31",
    "revenue_usd": 364000000000,
    "geo": "NE",
    "risk_band": "1-pass"
  },
  {
    "id": "BRW-FORD",
    "name": "Ford Motor Co.",
    "naics": "33",
    "revenue_usd": 158057000000,
    "geo": "MI",
    "risk_band": "2-special-mention"
  },
  {
    "id": "BRW-DEERE",
    "name": "Deere & Company",
    "naics": "33",
    "revenue_usd": 51716000000,
    "geo": "IL",
    "risk_band": "1-pass"
  },
  {
    "id": "BRW-CAT",
    "name": "Caterpillar Inc.",
    "naics": "33",
    "revenue_usd": 67060000000,
    "geo": "IL",
    "risk_band": "1-pass"
  },
  {
    "id": "BRW-GE",
    "name": "GE Aerospace",
    "naics": "33",
    "revenue_usd": 32879000000,
    "geo": "MA",
    "risk_band": "2-special-mention"
  },
  {
    "id": "BRW-HON",
    "name": "Honeywell International",
    "naics": "33",
    "revenue_usd": 36662000000,
    "geo": "NC",
    "risk_band": "1-pass"
  },
  {
    "id": "BRW-EAT",
    "name": "Eaton Corp.",
    "naics": "33",
    "revenue_usd": 23196000000,
    "geo": "OH",
    "risk_band": "1-pass"
  },
  {
    "id": "BRW-3M",
    "name": "3M Company",
    "naics": "33",
    "revenue_usd": 32681000000,
    "geo": "MN",
    "risk_band": "2-special-mention"
  },
  {
    "id": "BRW-EMR",
    "name": "Emerson Electric Co.",
    "naics": "33",
    "revenue_usd": 17492000000,
    "geo": "MO",
    "risk_band": "1-pass"
  },
  {
    "id": "BRW-PH",
    "name": "Parker Hannifin",
    "naics": "33",
    "revenue_usd": 19065000000,
    "geo": "OH",
    "risk_band": "1-pass"
  },
  {
    "id": "BRW-ITW",
    "name": "Illinois Tool Works",
    "naics": "33",
    "revenue_usd": 16106000000,
    "geo": "IL",
    "risk_band": "1-pass"
  }
];

export const PRIMARY_BORROWER = BORROWERS[0];

export interface CaseShape {
  canonical_id: string;
  title: string;
  primary_actor: string;
  decision_kind: string;
  stages: string[];
  key_metrics: string[];
}

export const CASE_SHAPE: CaseShape = {
  "canonical_id": "APP-2026-LECO-001",
  "title": "Lincoln Electric Holdings — $25M revolver",
  "primary_actor": "Relationship Manager",
  "decision_kind": "approve | decline | refer",
  "stages": [
    "intake",
    "extracting",
    "analyzing",
    "spreading",
    "rating",
    "drafting",
    "reviewing",
    "approval",
    "done"
  ],
  "key_metrics": [
    "DSCR",
    "leverage",
    "single_borrower_pct",
    "risk_band"
  ]
};

export const HITL_GATES = [
  "extraction_review",
  "rating_review",
  "draft_review",
  "final_approval"
];

export const ATOMIC_SERVICE_STUBS: Record<string, unknown> = {
  "financial-spreader": {
    "_stub": "financial-spreader",
    "_output_schema": false
  },
  "loan-serviceability": {
    "_stub": "loan-serviceability",
    "_output_schema": false
  },
  "peer-and-industry-context": {
    "_stub": "peer-and-industry-context",
    "_output_schema": false
  },
  "borrower-network": {
    "_stub": "borrower-network",
    "_output_schema": false
  },
  "collateral-valuator": {
    "_stub": "collateral-valuator",
    "_output_schema": false
  },
  "document-extractor": {
    "extracted_fields": {
      "fiscal_year_end": "2024-12-31",
      "currency": "USD",
      "units": "millions",
      "income_statement": {
        "revenue": 4233,
        "cogs": 2842,
        "ebitda": 804,
        "operating_income": 612,
        "depreciation_amortization": 192,
        "interest_expense": 34,
        "tax_expense": 134,
        "net_income": 444
      },
      "balance_sheet": {
        "total_assets": 3892,
        "current_assets": 1812,
        "cash_and_equivalents": 412,
        "accounts_receivable": 624,
        "inventory": 488,
        "ppe_net": 712,
        "total_liabilities": 1923,
        "current_liabilities": 882,
        "total_debt": 720,
        "long_term_debt": 642,
        "short_term_debt": 78,
        "total_equity": 1969
      },
      "cash_flow": {
        "operating_cash_flow": 712,
        "capex": 121,
        "free_cash_flow": 591
      },
      "customer_concentration": {
        "disclosed": true,
        "top_1_pct": 0.08,
        "top_5_pct": 0.24,
        "named_customers": []
      },
      "officers": [
        {
          "name": "Christopher L. Mapes",
          "title": "CEO",
          "tenure_years": 12
        },
        {
          "name": "Gabriel Bruno",
          "title": "CFO",
          "tenure_years": 4
        }
      ],
      "going_concern_qualification": false
    },
    "confidence": 0.93,
    "page_count": 240,
    "citations": [
      {
        "field_path": "income_statement.revenue",
        "chunk_id": "ch_42",
        "page": 18,
        "bbox": [
          0.1,
          0.2,
          0.6,
          0.25
        ],
        "excerpt": "Net sales totaled $4,233.0 million in 2024",
        "confidence": 0.96
      }
    ]
  }
};

export const AGENT_OUTPUT_STUBS: Record<string, unknown> = {
  "document-processor": {
    "_stub": "document-processor",
    "_archetype_loaded": true
  },
  "analyst-multisection": {
    "_stub": "analyst-multisection",
    "_archetype_loaded": true
  },
  "rater-with-covenant": {
    "_stub": "rater-with-covenant",
    "_archetype_loaded": true
  },
  "narrative-drafter": {
    "_stub": "narrative-drafter",
    "_archetype_loaded": true
  },
  "memo-reviewer-v2": {
    "_stub": "memo-reviewer-v2",
    "_archetype_loaded": true
  }
};

export const SHARED_RULES = [
  "dscr_threshold_by_industry",
  "leverage_threshold_by_industry",
  "single_borrower_exposure",
  "reg_o_individual_limit"
];

export const RULE_VERDICTS: Record<string, "pass" | "watch" | "fail" | "skip"> = {
  "dscr_threshold_by_industry": "pass",
  "leverage_threshold_by_industry": "pass",
  "single_borrower_exposure": "watch",
  "reg_o_individual_limit": "pass"
};

export const PIPELINE_EVENTS = [
  {
    "at": "2026-05-09T08:00:00.000Z",
    "kind": "stage_entered",
    "stage": "intake"
  },
  {
    "at": "2026-05-09T08:00:02.000Z",
    "kind": "document_uploaded",
    "doc_type": "10-K"
  },
  {
    "at": "2026-05-09T08:00:05.000Z",
    "kind": "document_uploaded",
    "doc_type": "AR_aging"
  },
  {
    "at": "2026-05-09T08:00:09.000Z",
    "kind": "stage_entered",
    "stage": "extracting"
  },
  {
    "at": "2026-05-09T08:00:54.000Z",
    "kind": "document_extracted",
    "doc_type": "10-K",
    "confidence": 0.94
  },
  {
    "at": "2026-05-09T08:01:02.000Z",
    "kind": "document_extracted",
    "doc_type": "AR_aging",
    "confidence": 0.91
  },
  {
    "at": "2026-05-09T08:01:04.000Z",
    "kind": "service_invoked",
    "service": "financial-spreader",
    "latency_ms": 831
  },
  {
    "at": "2026-05-09T08:01:06.000Z",
    "kind": "service_invoked",
    "service": "loan-serviceability",
    "latency_ms": 640
  },
  {
    "at": "2026-05-09T08:01:08.000Z",
    "kind": "service_invoked",
    "service": "peer-and-industry-context",
    "latency_ms": 436
  },
  {
    "at": "2026-05-09T08:01:10.000Z",
    "kind": "service_invoked",
    "service": "borrower-network",
    "latency_ms": 697
  },
  {
    "at": "2026-05-09T08:01:12.000Z",
    "kind": "service_invoked",
    "service": "collateral-valuator",
    "latency_ms": 775
  },
  {
    "at": "2026-05-09T08:01:14.000Z",
    "kind": "service_invoked",
    "service": "document-extractor",
    "latency_ms": 645
  },
  {
    "at": "2026-05-09T08:01:21.000Z",
    "kind": "agent_invoked",
    "agent": "document-processor",
    "tokens_in": 8000,
    "tokens_out": 3500
  },
  {
    "at": "2026-05-09T08:01:28.000Z",
    "kind": "agent_invoked",
    "agent": "analyst-multisection",
    "tokens_in": 8000,
    "tokens_out": 3500
  },
  {
    "at": "2026-05-09T08:01:35.000Z",
    "kind": "agent_invoked",
    "agent": "rater-with-covenant",
    "tokens_in": 8000,
    "tokens_out": 3500
  },
  {
    "at": "2026-05-09T08:01:42.000Z",
    "kind": "agent_invoked",
    "agent": "narrative-drafter",
    "tokens_in": 8000,
    "tokens_out": 3500
  },
  {
    "at": "2026-05-09T08:01:49.000Z",
    "kind": "agent_invoked",
    "agent": "memo-reviewer-v2",
    "tokens_in": 8000,
    "tokens_out": 3500
  },
  {
    "at": "2026-05-09T08:02:49.000Z",
    "kind": "human_action_pending",
    "gate": "extraction_review"
  },
  {
    "at": "2026-05-09T08:05:49.000Z",
    "kind": "human_action",
    "gate": "extraction_review",
    "decision": "approve"
  },
  {
    "at": "2026-05-09T08:06:49.000Z",
    "kind": "human_action_pending",
    "gate": "rating_review"
  },
  {
    "at": "2026-05-09T08:09:49.000Z",
    "kind": "human_action",
    "gate": "rating_review",
    "decision": "approve"
  },
  {
    "at": "2026-05-09T08:10:49.000Z",
    "kind": "human_action_pending",
    "gate": "draft_review"
  },
  {
    "at": "2026-05-09T08:13:49.000Z",
    "kind": "human_action",
    "gate": "draft_review",
    "decision": "approve"
  },
  {
    "at": "2026-05-09T08:14:49.000Z",
    "kind": "human_action_pending",
    "gate": "final_approval"
  },
  {
    "at": "2026-05-09T08:17:49.000Z",
    "kind": "human_action",
    "gate": "final_approval",
    "decision": "approve"
  },
  {
    "at": "2026-05-09T08:17:51.000Z",
    "kind": "stage_entered",
    "stage": "done"
  }
];

export const MODEL_PROVIDER = "hybrid";

export const COMPLIANCE_SCOPE = "full";

// A minimal "live case" that designers can render directly.
export const LIVE_CASE = {
  id: CASE_SHAPE.canonical_id,
  title: CASE_SHAPE.title,
  borrower: PRIMARY_BORROWER,
  current_stage: CASE_SHAPE.stages[CASE_SHAPE.stages.length - 1],
  decision: "approve",
  decision_kind: CASE_SHAPE.decision_kind,
  hitl_gates: HITL_GATES,
  events: PIPELINE_EVENTS,
  rule_verdicts: RULE_VERDICTS,
  service_results: ATOMIC_SERVICE_STUBS,
  agent_outputs: AGENT_OUTPUT_STUBS,
};

// END GENERATED.
