// THIS FILE IS GENERATED by scripts/generate_mock_canvas_data.mjs.
// Do not edit by hand; designer agents must IMPORT from this module
// (read-only). To regenerate after canvas changes:
//
//   node scripts/generate_mock_canvas_data.mjs payment-fraud-scoring-test
//
// Provenance:
//   use_case_id     = payment-fraud-scoring-test
//   canvas_sha256   = cc47591b9d1241218f08426db4fc4f8d5ab013c34dcbae526d7d104d502c15b1
//   generated_at    = 2026-05-11T04:35:00.860Z
//   console_pattern = real-time

export const USE_CASE_ID = "payment-fraud-scoring-test";
export const CANVAS_SHA256 = "cc47591b9d1241218f08426db4fc4f8d5ab013c34dcbae526d7d104d502c15b1";
export const CONSOLE_PATTERN = "real-time";

export interface Borrower {
  id: string;
  name: string;
  naics: string;
  revenue_usd: number;
  geo: string;
  risk_band: string;
}

export const BORROWERS: Borrower[] = [
  {
    "id": "BRW-LECO",
    "name": "Lincoln Electric Holdings",
    "naics": "33",
    "revenue_usd": 4184000000,
    "geo": "OH",
    "risk_band": "1-pass"
  },
  {
    "id": "BRW-BRK",
    "name": "Berkshire Industrial Holdings",
    "naics": "31",
    "revenue_usd": 364000000000,
    "geo": "NE",
    "risk_band": "1-pass"
  },
  {
    "id": "BRW-FORD",
    "name": "Ford Motor Co.",
    "naics": "33",
    "revenue_usd": 158057000000,
    "geo": "MI",
    "risk_band": "2-special-mention"
  },
  {
    "id": "BRW-DEERE",
    "name": "Deere & Company",
    "naics": "33",
    "revenue_usd": 51716000000,
    "geo": "IL",
    "risk_band": "1-pass"
  },
  {
    "id": "BRW-CAT",
    "name": "Caterpillar Inc.",
    "naics": "33",
    "revenue_usd": 67060000000,
    "geo": "IL",
    "risk_band": "1-pass"
  },
  {
    "id": "BRW-GE",
    "name": "GE Aerospace",
    "naics": "33",
    "revenue_usd": 32879000000,
    "geo": "MA",
    "risk_band": "2-special-mention"
  },
  {
    "id": "BRW-HON",
    "name": "Honeywell International",
    "naics": "33",
    "revenue_usd": 36662000000,
    "geo": "NC",
    "risk_band": "1-pass"
  },
  {
    "id": "BRW-EAT",
    "name": "Eaton Corp.",
    "naics": "33",
    "revenue_usd": 23196000000,
    "geo": "OH",
    "risk_band": "1-pass"
  },
  {
    "id": "BRW-3M",
    "name": "3M Company",
    "naics": "33",
    "revenue_usd": 32681000000,
    "geo": "MN",
    "risk_band": "2-special-mention"
  },
  {
    "id": "BRW-EMR",
    "name": "Emerson Electric Co.",
    "naics": "33",
    "revenue_usd": 17492000000,
    "geo": "MO",
    "risk_band": "1-pass"
  },
  {
    "id": "BRW-PH",
    "name": "Parker Hannifin",
    "naics": "33",
    "revenue_usd": 19065000000,
    "geo": "OH",
    "risk_band": "1-pass"
  },
  {
    "id": "BRW-ITW",
    "name": "Illinois Tool Works",
    "naics": "33",
    "revenue_usd": 16106000000,
    "geo": "IL",
    "risk_band": "1-pass"
  }
];

export const PRIMARY_BORROWER = BORROWERS[0];

export interface CaseShape {
  canonical_id: string;
  title: string;
  primary_actor: string;
  decision_kind: string;
  stages: string[];
  key_metrics: string[];
}

export const CASE_SHAPE: CaseShape = {
  "canonical_id": "EVT-1715350200-7f3a",
  "title": "POS auth — $2,847 at Walmart Supercenter",
  "primary_actor": "Fraud Ops",
  "decision_kind": "approve | decline | step-up",
  "stages": [
    "received",
    "scored",
    "decided",
    "settled"
  ],
  "key_metrics": [
    "score",
    "model_confidence",
    "feature_drift_pct"
  ]
};

export const HITL_GATES = [];

export const ATOMIC_SERVICE_STUBS: Record<string, unknown> = {
  "industry-risk-scorer": {
    "_stub": "industry-risk-scorer",
    "_output_schema": false
  },
  "peer-and-industry-context": {
    "_stub": "peer-and-industry-context",
    "_output_schema": false
  }
};

export const AGENT_OUTPUT_STUBS: Record<string, unknown> = {
  "gray-zone-fraud-scorer": {
    "_stub": "gray-zone-fraud-scorer",
    "_archetype_loaded": true
  }
};

export const SHARED_RULES = [];

export const RULE_VERDICTS: Record<string, "pass" | "watch" | "fail" | "skip"> = {

};

export const PIPELINE_EVENTS = [
  {
    "at": "2026-05-09T08:00:00.000Z",
    "kind": "stage_entered",
    "stage": "intake"
  },
  {
    "at": "2026-05-09T08:00:02.000Z",
    "kind": "document_uploaded",
    "doc_type": "10-K"
  },
  {
    "at": "2026-05-09T08:00:05.000Z",
    "kind": "document_uploaded",
    "doc_type": "AR_aging"
  },
  {
    "at": "2026-05-09T08:00:09.000Z",
    "kind": "stage_entered",
    "stage": "extracting"
  },
  {
    "at": "2026-05-09T08:00:54.000Z",
    "kind": "document_extracted",
    "doc_type": "10-K",
    "confidence": 0.94
  },
  {
    "at": "2026-05-09T08:01:02.000Z",
    "kind": "document_extracted",
    "doc_type": "AR_aging",
    "confidence": 0.91
  },
  {
    "at": "2026-05-09T08:01:04.000Z",
    "kind": "service_invoked",
    "service": "industry-risk-scorer",
    "latency_ms": 847
  },
  {
    "at": "2026-05-09T08:01:06.000Z",
    "kind": "service_invoked",
    "service": "peer-and-industry-context",
    "latency_ms": 436
  },
  {
    "at": "2026-05-09T08:01:13.000Z",
    "kind": "agent_invoked",
    "agent": "gray-zone-fraud-scorer",
    "tokens_in": 8000,
    "tokens_out": 3500
  },
  {
    "at": "2026-05-09T08:01:15.000Z",
    "kind": "stage_entered",
    "stage": "done"
  }
];

export const MODEL_PROVIDER = "vertex_gemini";

export const COMPLIANCE_SCOPE = "lightweight";

// A minimal "live case" that designers can render directly.
export const LIVE_CASE = {
  id: CASE_SHAPE.canonical_id,
  title: CASE_SHAPE.title,
  borrower: PRIMARY_BORROWER,
  current_stage: CASE_SHAPE.stages[CASE_SHAPE.stages.length - 1],
  decision: "approve",
  decision_kind: CASE_SHAPE.decision_kind,
  hitl_gates: HITL_GATES,
  events: PIPELINE_EVENTS,
  rule_verdicts: RULE_VERDICTS,
  service_results: ATOMIC_SERVICE_STUBS,
  agent_outputs: AGENT_OUTPUT_STUBS,
};

// END GENERATED.
