// THIS FILE IS GENERATED by scripts/generate_mock_canvas_data.mjs.
// Do not edit by hand; designer agents must IMPORT from this module
// (read-only). To regenerate after canvas changes:
//
//   node scripts/generate_mock_canvas_data.mjs cecl-quarterly-run-test
//
// Provenance:
//   use_case_id     = cecl-quarterly-run-test
//   canvas_sha256   = 91f47921f8c50735facca5d50696e98661c7111fba41cbcb0ae0f1ebb7848b27
//   generated_at    = 2026-05-11T05:47:42.710Z
//   console_pattern = run

export const USE_CASE_ID = "cecl-quarterly-run-test";
export const CANVAS_SHA256 = "91f47921f8c50735facca5d50696e98661c7111fba41cbcb0ae0f1ebb7848b27";
export const CONSOLE_PATTERN = "run";

export interface Borrower {
  id: string;
  name: string;
  naics: string;
  revenue_usd: number;
  geo: string;
  risk_band: string;
}

export const BORROWERS: Borrower[] = [
  {
    "id": "BRW-LECO",
    "name": "Lincoln Electric Holdings",
    "naics": "33",
    "revenue_usd": 4184000000,
    "geo": "OH",
    "risk_band": "1-pass"
  },
  {
    "id": "BRW-BRK",
    "name": "Berkshire Industrial Holdings",
    "naics": "31",
    "revenue_usd": 364000000000,
    "geo": "NE",
    "risk_band": "1-pass"
  },
  {
    "id": "BRW-FORD",
    "name": "Ford Motor Co.",
    "naics": "33",
    "revenue_usd": 158057000000,
    "geo": "MI",
    "risk_band": "2-special-mention"
  },
  {
    "id": "BRW-DEERE",
    "name": "Deere & Company",
    "naics": "33",
    "revenue_usd": 51716000000,
    "geo": "IL",
    "risk_band": "1-pass"
  },
  {
    "id": "BRW-CAT",
    "name": "Caterpillar Inc.",
    "naics": "33",
    "revenue_usd": 67060000000,
    "geo": "IL",
    "risk_band": "1-pass"
  },
  {
    "id": "BRW-GE",
    "name": "GE Aerospace",
    "naics": "33",
    "revenue_usd": 32879000000,
    "geo": "MA",
    "risk_band": "2-special-mention"
  },
  {
    "id": "BRW-HON",
    "name": "Honeywell International",
    "naics": "33",
    "revenue_usd": 36662000000,
    "geo": "NC",
    "risk_band": "1-pass"
  },
  {
    "id": "BRW-EAT",
    "name": "Eaton Corp.",
    "naics": "33",
    "revenue_usd": 23196000000,
    "geo": "OH",
    "risk_band": "1-pass"
  },
  {
    "id": "BRW-3M",
    "name": "3M Company",
    "naics": "33",
    "revenue_usd": 32681000000,
    "geo": "MN",
    "risk_band": "2-special-mention"
  },
  {
    "id": "BRW-EMR",
    "name": "Emerson Electric Co.",
    "naics": "33",
    "revenue_usd": 17492000000,
    "geo": "MO",
    "risk_band": "1-pass"
  },
  {
    "id": "BRW-PH",
    "name": "Parker Hannifin",
    "naics": "33",
    "revenue_usd": 19065000000,
    "geo": "OH",
    "risk_band": "1-pass"
  },
  {
    "id": "BRW-ITW",
    "name": "Illinois Tool Works",
    "naics": "33",
    "revenue_usd": 16106000000,
    "geo": "IL",
    "risk_band": "1-pass"
  }
];

export const PRIMARY_BORROWER = BORROWERS[0];

export interface CaseShape {
  canonical_id: string;
  title: string;
  primary_actor: string;
  decision_kind: string;
  stages: string[];
  key_metrics: string[];
}

export const CASE_SHAPE: CaseShape = {
  "canonical_id": "RUN-CECL-2026Q2",
  "title": "CECL Q2 reserve calculation",
  "primary_actor": "Risk Analytics Lead",
  "decision_kind": "publish | adjust | rerun",
  "stages": [
    "queued",
    "running",
    "review",
    "published"
  ],
  "key_metrics": [
    "pd",
    "lgd",
    "ead",
    "ecl"
  ]
};

export const HITL_GATES = [
  {
    "name": "approve_segment_methodology",
    "irrevocable": false,
    "description": "Methodology owner approves segment-level PD/LGD model selection"
  },
  {
    "name": "cfo_attest_run",
    "irrevocable": true,
    "description": "CFO attests the final allowance figure (regulator-visible)"
  }
];

export const ATOMIC_SERVICE_STUBS: Record<string, unknown> = {
  "financial-spreader": {
    "_stub": "financial-spreader",
    "_output_schema": false
  },
  "industry-risk-scorer": {
    "_stub": "industry-risk-scorer",
    "_output_schema": false
  }
};

export const AGENT_OUTPUT_STUBS: Record<string, unknown> = {};

export const SHARED_RULES = [];

export const RULE_VERDICTS: Record<string, "pass" | "watch" | "fail" | "skip"> = {

};

export const PIPELINE_EVENTS = [
  {
    "at": "2026-05-09T08:00:00.000Z",
    "kind": "stage_entered",
    "stage": "intake"
  },
  {
    "at": "2026-05-09T08:00:02.000Z",
    "kind": "document_uploaded",
    "doc_type": "10-K"
  },
  {
    "at": "2026-05-09T08:00:05.000Z",
    "kind": "document_uploaded",
    "doc_type": "AR_aging"
  },
  {
    "at": "2026-05-09T08:00:09.000Z",
    "kind": "stage_entered",
    "stage": "extracting"
  },
  {
    "at": "2026-05-09T08:00:54.000Z",
    "kind": "document_extracted",
    "doc_type": "10-K",
    "confidence": 0.94
  },
  {
    "at": "2026-05-09T08:01:02.000Z",
    "kind": "document_extracted",
    "doc_type": "AR_aging",
    "confidence": 0.91
  },
  {
    "at": "2026-05-09T08:01:04.000Z",
    "kind": "service_invoked",
    "service": "financial-spreader",
    "latency_ms": 831
  },
  {
    "at": "2026-05-09T08:01:06.000Z",
    "kind": "service_invoked",
    "service": "industry-risk-scorer",
    "latency_ms": 847
  },
  {
    "at": "2026-05-09T08:02:06.000Z",
    "kind": "human_action_pending",
    "gate": {
      "name": "approve_segment_methodology",
      "irrevocable": false,
      "description": "Methodology owner approves segment-level PD/LGD model selection"
    }
  },
  {
    "at": "2026-05-09T08:05:06.000Z",
    "kind": "human_action",
    "gate": {
      "name": "approve_segment_methodology",
      "irrevocable": false,
      "description": "Methodology owner approves segment-level PD/LGD model selection"
    },
    "decision": "approve"
  },
  {
    "at": "2026-05-09T08:06:06.000Z",
    "kind": "human_action_pending",
    "gate": {
      "name": "cfo_attest_run",
      "irrevocable": true,
      "description": "CFO attests the final allowance figure (regulator-visible)"
    }
  },
  {
    "at": "2026-05-09T08:09:06.000Z",
    "kind": "human_action",
    "gate": {
      "name": "cfo_attest_run",
      "irrevocable": true,
      "description": "CFO attests the final allowance figure (regulator-visible)"
    },
    "decision": "approve"
  },
  {
    "at": "2026-05-09T08:09:08.000Z",
    "kind": "stage_entered",
    "stage": "done"
  }
];

export const MODEL_PROVIDER = "vertex_gemini";

export const COMPLIANCE_SCOPE = "high";

// A minimal "live case" that designers can render directly.
export const LIVE_CASE = {
  id: CASE_SHAPE.canonical_id,
  title: CASE_SHAPE.title,
  borrower: PRIMARY_BORROWER,
  current_stage: CASE_SHAPE.stages[CASE_SHAPE.stages.length - 1],
  decision: "approve",
  decision_kind: CASE_SHAPE.decision_kind,
  hitl_gates: HITL_GATES,
  events: PIPELINE_EVENTS,
  rule_verdicts: RULE_VERDICTS,
  service_results: ATOMIC_SERVICE_STUBS,
  agent_outputs: AGENT_OUTPUT_STUBS,
};

// END GENERATED.
