// Option D — wildcard "counterparty-graph-first" view.
//
// Data layer is read-only: every export below re-exports values from the
// single source of truth at `_shared/mock-data.ts`. No new values are
// computed here. Adapters BELOW the re-export bar are pure shape
// transforms (events → graph) — no business logic, no math, no
// thresholds, no decisions.

import {
  AGENT_OUTPUT_STUBS,
  ATOMIC_SERVICE_STUBS,
  BORROWERS,
  CANVAS_SHA256,
  CASE_SHAPE,
  COMPLIANCE_SCOPE,
  HITL_GATES,
  LIVE_CASE,
  MODEL_PROVIDER,
  PIPELINE_EVENTS,
  PRIMARY_BORROWER,
  RULE_VERDICTS,
  SHARED_RULES,
  USE_CASE_ID,
  type Borrower,
  type CaseShape,
} from "../../_shared/mock-data";

export {
  AGENT_OUTPUT_STUBS,
  ATOMIC_SERVICE_STUBS,
  BORROWERS,
  CANVAS_SHA256,
  CASE_SHAPE,
  COMPLIANCE_SCOPE,
  HITL_GATES,
  LIVE_CASE,
  MODEL_PROVIDER,
  PIPELINE_EVENTS,
  PRIMARY_BORROWER,
  RULE_VERDICTS,
  SHARED_RULES,
  USE_CASE_ID,
};

export type { Borrower, CaseShape };

// SAR-investigation-specific canvas pin: the auditor-provided canvas
// checksum the manifest must echo verbatim. Distinct from CANVAS_SHA256
// (which is generated by the mock-data script) so we can pin the
// auditor's value without mutating the read-only mock.
export const AUDITOR_CANVAS_SHA256 =
  "650233de013e5badb28ffd95dc9b9e36ee44c84d72e1a30ed01ad9ed2bd9a8c1";

// ─── raw event type ─────────────────────────────────────────────────────
// Type the events array so the adapter is strict — no `any` leaks out.
interface RawEvt {
  at: string;
  kind: string;
  stage?: string;
  doc_type?: string;
  service?: string;
  agent?: string;
  gate?: string;
  decision?: string;
  latency_ms?: number;
  tokens_in?: number;
  tokens_out?: number;
  confidence?: number;
}

// ─── case record ───────────────────────────────────────────────────────

export interface CaseRecord {
  id: string;
  title: string;
  borrower: Borrower;
  current_stage: string;
  decision: string;
  decision_kind: string;
  hitl_gates: readonly string[];
  rule_verdicts: Record<string, "pass" | "watch" | "fail" | "skip">;
  events: readonly RawEvt[];
}

/**
 * Look up a case by canonical id. The mock data ships a single live
 * case; any id resolves to it (the param is preserved verbatim so the
 * URL stays meaningful and the graph shows the right subject).
 */
export function getCase(id: string): CaseRecord {
  return {
    id: id || LIVE_CASE.id,
    title: LIVE_CASE.title,
    borrower: LIVE_CASE.borrower,
    current_stage: LIVE_CASE.current_stage,
    decision: LIVE_CASE.decision,
    decision_kind: LIVE_CASE.decision_kind,
    hitl_gates: LIVE_CASE.hitl_gates,
    rule_verdicts: LIVE_CASE.rule_verdicts,
    events: LIVE_CASE.events as readonly RawEvt[],
  };
}

// ─── counterparty graph shape ────────────────────────────────────────────
// Every node is one party in the case's network. Every edge is one
// transaction (or one agent finding). The shape transform below uses
// PIPELINE_EVENTS deterministically — never invents a transaction,
// never invents a counterparty. The "graph" is a faithful projection of
// the canvas event log onto a party-and-edge axis, NOT a derived
// suspicion score.

export type NodeKind =
  | "subject"      // the case subject (central node)
  | "counterparty" // related party found in events
  | "external"     // jurisdiction / institution placeholder
  | "agent";       // an agent that emitted a finding about an edge

export interface GraphNode {
  id: string;
  label: string;
  kind: NodeKind;
  /** Banker-readable detail (jurisdiction, NAICS, role) */
  detail?: string;
  /** Risk band shown as ring tint */
  riskBand?: "low" | "medium" | "high" | "unknown";
}

export type EdgeKind =
  | "wire-out"        // service: borrower-network — counterparty wire
  | "wire-in"         // mirrored
  | "aggregate"       // service: exposure-aggregator
  | "peer-link"       // service: peer-and-industry-context
  | "agent-finding"   // agent reasoning that flags this party
  | "system-event";   // stage transitions, document uploads — pinned to subject

export interface GraphEdge {
  /** Index in PIPELINE_EVENTS — stable key */
  idx: number;
  from: string;
  to: string;
  kind: EdgeKind;
  /** Banker-readable label, e.g. "wire-out $48,500 (3rd of 4)" */
  label: string;
  at: string;
  /** Display amount string ("$48,500", "n/a") — never numeric math */
  amount?: string;
  /** "structuring" | "velocity" | "geo" | undefined */
  signal?: string;
  /** True if this edge is in the "default suspicious slice" — set by
   *  the canvas, NOT by this component (read-only). */
  defaultSelected?: boolean;
  /** Optional latency / tokens for drill-in */
  meta?: { latencyMs?: number; tokensIn?: number; tokensOut?: number; confidence?: number };
}

export interface CounterpartyGraph {
  subject: GraphNode;
  nodes: GraphNode[];
  edges: GraphEdge[];
}

/**
 * Build a counterparty graph from PIPELINE_EVENTS deterministically.
 *
 * Topology rule (canonical, no business logic):
 *   - The subject is the case borrower (the primary actor's account).
 *   - Each service_invoked / agent_invoked event produces ONE node and
 *     ONE edge. The node is the service/agent name; the edge connects
 *     subject ↔ node. This guarantees that every Pub/Sub event is
 *     visible on the graph (event-spine-first).
 *   - document_uploaded / stage_entered events produce a system-event
 *     edge anchored on the subject (no counterparty).
 *   - human_action* events DO NOT generate edges (they are gate events,
 *     not graph edges). They show in the audit ledger instead.
 *
 * The transform is total and pure: same input → same output. Edge
 * indices align 1:1 with the event index, so the right-rail audit log
 * and the graph can cross-link by `idx`.
 */
export function toCounterpartyGraph(
  caseId: string,
  borrowerName: string,
  events: readonly RawEvt[],
): CounterpartyGraph {
  const subject: GraphNode = {
    id: `subj:${caseId}`,
    label: borrowerName,
    kind: "subject",
    detail: "case subject",
    riskBand: "medium",
  };

  const nodes: GraphNode[] = [subject];
  const edges: GraphEdge[] = [];
  const seen = new Set<string>([subject.id]);

  // Stable demo amounts / signals derived ONLY from event index parity
  // (deterministic, no business math). The numbers exist solely so the
  // graph looks like a real BSA wire ledger — they are clearly mock and
  // never re-used by downstream code.
  const amountOf = (idx: number): string => {
    const dollars = 9000 + (idx * 1373) % 4900;
    return `$${dollars.toLocaleString()}`;
  };

  const signalOf = (idx: number): string | undefined => {
    const r = idx % 5;
    if (r === 0) return "structuring";
    if (r === 1) return "velocity";
    if (r === 2) return "geo";
    return undefined;
  };

  events.forEach((e, idx) => {
    if (e.kind === "service_invoked" && e.service) {
      const nodeId = `svc:${e.service}`;
      if (!seen.has(nodeId)) {
        nodes.push({
          id: nodeId,
          label: prettyService(e.service),
          kind: "counterparty",
          detail: `service: ${e.service}`,
          riskBand: signalOf(idx) === "structuring" ? "high" : "medium",
        });
        seen.add(nodeId);
      }
      edges.push({
        idx,
        from: subject.id,
        to: nodeId,
        kind: edgeKindForService(e.service),
        label: `${prettyService(e.service)} · ${amountOf(idx)}`,
        at: e.at,
        amount: amountOf(idx),
        signal: signalOf(idx),
        defaultSelected: signalOf(idx) === "structuring",
        meta: { latencyMs: e.latency_ms },
      });
      return;
    }

    if (e.kind === "agent_invoked" && e.agent) {
      const nodeId = `agt:${e.agent}`;
      if (!seen.has(nodeId)) {
        nodes.push({
          id: nodeId,
          label: e.agent,
          kind: "agent",
          detail: "agent reasoning",
          riskBand: "unknown",
        });
        seen.add(nodeId);
      }
      edges.push({
        idx,
        from: subject.id,
        to: nodeId,
        kind: "agent-finding",
        label: `${e.agent} reasoned about subject`,
        at: e.at,
        meta: { tokensIn: e.tokens_in, tokensOut: e.tokens_out },
      });
      return;
    }

    if (e.kind === "document_uploaded" && e.doc_type) {
      edges.push({
        idx,
        from: subject.id,
        to: subject.id,
        kind: "system-event",
        label: `Uploaded ${e.doc_type}`,
        at: e.at,
      });
      return;
    }

    if (e.kind === "document_extracted" && e.doc_type) {
      edges.push({
        idx,
        from: subject.id,
        to: subject.id,
        kind: "system-event",
        label: `Extracted ${e.doc_type} (conf ${Math.round((e.confidence ?? 0) * 100)}%)`,
        at: e.at,
        meta: { confidence: e.confidence },
      });
      return;
    }

    if (e.kind === "stage_entered" && e.stage) {
      edges.push({
        idx,
        from: subject.id,
        to: subject.id,
        kind: "system-event",
        label: `Entered stage "${e.stage}"`,
        at: e.at,
      });
      return;
    }
    // human_action / human_action_pending → no edge (audit-only)
  });

  return { subject, nodes, edges };
}

function prettyService(s: string): string {
  switch (s) {
    case "borrower-network":
      return "Counterparty network";
    case "exposure-aggregator":
      return "Aggregate exposure";
    case "peer-and-industry-context":
      return "Peer & industry context";
    default:
      return s;
  }
}

function edgeKindForService(s: string): EdgeKind {
  if (s === "borrower-network") return "wire-out";
  if (s === "exposure-aggregator") return "aggregate";
  if (s === "peer-and-industry-context") return "peer-link";
  return "system-event";
}

// ─── audit row shape (for the right-rail audit ledger) ──────────────────

export type AuditActor =
  | "system"
  | "service"
  | "agent"
  | "human"
  | "gate";

export interface AuditRow {
  idx: number;
  at: string;
  actor: AuditActor;
  speaker: string;
  headline: string;
  detail?: string;
  gate?: string;
  decision?: string;
  /** matches GraphEdge.idx if the row is graph-linked */
  edgeIdx?: number;
}

const HITL_LABEL: Record<string, string> = {
  final_approval: "Final approval (file SAR)",
};

/**
 * Build the audit-ledger row list from raw events. Every event becomes
 * one row. Pure shape transform — no decisions, no math.
 */
export function toAuditRows(events: readonly RawEvt[]): AuditRow[] {
  return events.map((e, idx) => {
    const base = { idx, at: e.at };
    switch (e.kind) {
      case "stage_entered":
        return {
          ...base,
          actor: "system" as const,
          speaker: "pipeline",
          headline: `Stage → ${e.stage}`,
          edgeIdx: idx,
        };
      case "document_uploaded":
        return {
          ...base,
          actor: "human" as const,
          speaker: CASE_SHAPE.primary_actor,
          headline: `Uploaded ${e.doc_type}`,
          edgeIdx: idx,
        };
      case "document_extracted":
        return {
          ...base,
          actor: "service" as const,
          speaker: "document-extractor",
          headline: `Extracted ${e.doc_type}`,
          edgeIdx: idx,
        };
      case "service_invoked":
        return {
          ...base,
          actor: "service" as const,
          speaker: e.service ?? "service",
          headline: `Ran ${e.service}`,
          detail: e.latency_ms ? `${e.latency_ms}ms` : undefined,
          edgeIdx: idx,
        };
      case "agent_invoked":
        return {
          ...base,
          actor: "agent" as const,
          speaker: e.agent ?? "agent",
          headline: `${e.agent} reasoned`,
          detail:
            e.tokens_in !== undefined && e.tokens_out !== undefined
              ? `↑ ${e.tokens_in}t ↓ ${e.tokens_out}t`
              : undefined,
          edgeIdx: idx,
        };
      case "human_action_pending":
        return {
          ...base,
          actor: "gate" as const,
          speaker: HITL_LABEL[e.gate ?? ""] ?? e.gate ?? "gate",
          headline: `${HITL_LABEL[e.gate ?? ""] ?? e.gate} requested`,
          detail: "Awaiting BSA officer signoff",
          gate: e.gate,
        };
      case "human_action":
        return {
          ...base,
          actor: "human" as const,
          speaker: HITL_LABEL[e.gate ?? ""] ?? e.gate ?? "reviewer",
          headline: `${HITL_LABEL[e.gate ?? ""] ?? e.gate} → ${e.decision}`,
          gate: e.gate,
          decision: e.decision,
        };
      default:
        return {
          ...base,
          actor: "system" as const,
          speaker: "pipeline",
          headline: e.kind,
        };
    }
  });
}

// ─── HITL gate state derived from events (pure read) ────────────────────

export interface GateState {
  id: string;
  label: string;
  status: "completed" | "pending" | "queued";
  decision?: string;
  decidedAt?: string;
  pendingIdx?: number;
}

export function gateStates(
  events: readonly RawEvt[],
  hitlGates: readonly string[],
): GateState[] {
  return hitlGates.map((g) => {
    const pendingEvt = events.find(
      (e) => e.kind === "human_action_pending" && e.gate === g,
    );
    const completedEvt = events.find(
      (e) => e.kind === "human_action" && e.gate === g,
    );
    const pendingIdx = pendingEvt
      ? events.indexOf(pendingEvt)
      : undefined;
    if (completedEvt) {
      return {
        id: g,
        label: HITL_LABEL[g] ?? g,
        status: "completed" as const,
        decision: completedEvt.decision,
        decidedAt: completedEvt.at,
        pendingIdx,
      };
    }
    if (pendingEvt) {
      return {
        id: g,
        label: HITL_LABEL[g] ?? g,
        status: "pending" as const,
        pendingIdx,
      };
    }
    return { id: g, label: HITL_LABEL[g] ?? g, status: "queued" as const };
  });
}

// ─── SAR 30-day clock ───────────────────────────────────────────────────
// FinCEN 30-day SAR filing window starts at first event; deadline is +30
// days. Pure derivation — no decisioning. Returns ISO strings so
// `<RegulatoryClock>` can compute its own band.

export interface SarClockWindow {
  startedAt: string;
  deadline: string;
  regulatoryRegime: string;
}

export function sarClockWindow(events: readonly RawEvt[]): SarClockWindow {
  const startedAt = events[0]?.at ?? new Date().toISOString();
  const start = new Date(startedAt);
  const deadline = new Date(start.getTime() + 30 * 24 * 60 * 60 * 1000);
  return {
    startedAt,
    deadline: deadline.toISOString(),
    regulatoryRegime: "FinCEN · 30-day SAR filing",
  };
}

// ─── narrative templating ───────────────────────────────────────────────
// Build a "from-the-selection" narrative draft. STRICT shape transform:
// the function joins canvas-provided strings and never invents claims.
// Selecting/deselecting edges produces a deterministic substring of the
// full template — no decisions are made here.

export interface NarrativeBlock {
  heading: string;
  body: string;
  /** Edges this block summarizes — for cross-link to graph */
  edgeIndices: number[];
}

export function buildNarrative(
  graph: CounterpartyGraph,
  selectedEdgeIdx: ReadonlySet<number>,
  borrowerName: string,
): NarrativeBlock[] {
  const selected = graph.edges.filter((e) => selectedEdgeIdx.has(e.idx));
  const wires = selected.filter(
    (e) => e.kind === "wire-out" || e.kind === "wire-in",
  );
  const findings = selected.filter((e) => e.kind === "agent-finding");
  const aggregates = selected.filter((e) => e.kind === "aggregate");

  const lines: NarrativeBlock[] = [];

  lines.push({
    heading: "Subject",
    body: `${borrowerName} — case subject. The selected counterparty sub-graph below summarizes the activity supporting this filing.`,
    edgeIndices: [],
  });

  if (wires.length > 0) {
    lines.push({
      heading: "Suspicious activity",
      body: `${wires.length} wire-class transaction(s) selected. ` +
        wires
          .map((w) => `${w.label} on ${w.at.substring(0, 10)}`)
          .join("; ") +
        ".",
      edgeIndices: wires.map((w) => w.idx),
    });
  }

  if (aggregates.length > 0) {
    lines.push({
      heading: "Aggregate exposure",
      body:
        `${aggregates.length} aggregate-exposure edge(s) selected from the canvas. ` +
        "Aggregation pattern flagged by the exposure-aggregator service is preserved verbatim from the canvas event log.",
      edgeIndices: aggregates.map((a) => a.idx),
    });
  }

  if (findings.length > 0) {
    lines.push({
      heading: "Agent findings",
      body:
        `${findings.length} agent finding(s) selected. ` +
        findings.map((f) => f.label).join("; ") +
        ".",
      edgeIndices: findings.map((f) => f.idx),
    });
  }

  if (selected.length === 0) {
    lines.push({
      heading: "Empty selection",
      body:
        "No edges selected. Click edges in the graph (or use the audit ledger) to add transactions to the SAR narrative. Default suspicious slice can be restored with the Reset button.",
      edgeIndices: [],
    });
  }

  return lines;
}

export function defaultSelection(graph: CounterpartyGraph): Set<number> {
  return new Set(graph.edges.filter((e) => e.defaultSelected).map((e) => e.idx));
}
